### ISSUE TITLE
ImportError: No module named 'lens'

### ISSUE THREAD

**Issue by Hamm1337** [Sterncat/opticspy#17]
- Pip version: pip 9.0.1
- Python version: 3.5.3
- Operating system: Windows 7

I copied out your example from:
http://sterncat.github.io/files/Real_Ray_Tracing.html

```
import matplotlib.pyplot as plt
from opticspy.ray_tracing import *
New_Lens = lens.Lens(lens_name='Triplet',creator='XF')
New_Lens.FNO = 5
New_Lens.lens_info()

New_Lens.add_wavelength(wl = 656.30)
New_Lens.add_wavelength(wl = 587.60)
New_Lens.add_wavelength(wl = 486.10)
New_Lens.list_wavelengths()

New_Lens.add_field_YAN(angle=0)
New_Lens.add_field_YAN(angle=14)
New_Lens.add_field_YAN(angle=20)
New_Lens.list_fields()

New_Lens.add_surface(number=1,radius=10000000,thickness=1000000,glass='air',output=True)
New_Lens.add_surface(number=2,radius=41.15909,thickness=6.097555 ,glass='S-BSM18_ohara',output=True)
New_Lens.add_surface(number=3,radius=-957.83146,thickness=9.349584,glass='air',output=True)
New_Lens.add_surface(number=4,radius=-51.32104,thickness=2.032518,glass='N-SF2_schott',output=True)
New_Lens.add_surface(number=5,radius=42.37768 ,thickness=5.995929 ,glass='air',output=True)
New_Lens.add_surface(number=6,radius=10000000,thickness=4.065037,glass='air',STO=True,output=True)
New_Lens.add_surface(number=7,radius=247.44562,thickness=6.097555,glass='S-BSM18_ohara',output=True)
New_Lens.add_surface(number=8,radius=-40.04016,thickness=85.593426,glass='air',output=True)
New_Lens.add_surface(number=9,radius=10000000,thickness=0,glass='air',output=True)

New_Lens.refresh_paraxial()

dict_list = trace.trace_draw_ray(New_Lens)
draw.draw_system(New_Lens)
```

Unfortunately I was getting a few different errors, initially realised I had an older version, fixed that and downloaded the new files, but now i get the following:

```
RESTART: E:\WinPython-64bit-3.5.3.0Qt5\python-3.5.3.amd64\Lib\site-packages\opticspy\Opticspy Project\Triplet.py 
Traceback (most recent call last):
  File "E:\WinPython-64bit-3.5.3.0Qt5\python-3.5.3.amd64\Lib\site-packages\opticspy\Opticspy Project\Triplet.py", line 2, in <module>
    from opticspy.ray_tracing import *
  File "E:\WinPython-64bit-3.5.3.0Qt5\python-3.5.3.amd64\lib\site-packages\opticspy\ray_tracing\__init__.py", line 1, in <module>
    from . import lens, trace, glass_function, draw, analysis, field, codev
  File "E:\WinPython-64bit-3.5.3.0Qt5\python-3.5.3.amd64\lib\site-packages\opticspy\ray_tracing\codev.py", line 1, in <module>
    import lens
ImportError: No module named 'lens'
>>>
```
I made sure to put my project folder into the opticspy folder, and i certainly have the lens.py file as well as the others in the ray_tracing folder. I took a screenshot and uploaded it here: http://imgur.com/a/0bM5Z

Thanks very much for the help and the wonderful module, I am excited to try it further!

**Comment by Hamm1337** [comment]
What I am looking to do, is use this to send a beam of rays in the form of "white light" onto a lens, (sphere of water, refract the rays depending on their wavelength, then reflect off a back mirror, and finally refract again through a second lens (same sphere of water) to show white light splitting in a raindrop to produce a rainbow

**Comment by Sterncat** [comment]
Hi ,

In opticspy, raytracing is still a really simple part. I will try to fix
the problem. But the thing what you are trying to do wouldn't be achieved
by opticspy. You could try "rayopt" in github or more professional software
like CodeV and Zemax. Thank you!

Sorry for I am really busy these days, so fix the problem maybe late.

Thank you!

Best regards,

Sterncat

2017-02-24 6:40 GMT+08:00 Hamm1337 <notifications@github.com>:

**Comment by boerndl** [comment]
I get a similar error message.

Upon evaluating the line

`from opticspy.ray_tracing import *`

I get

`ImportError: No module named 'aperture'`

The script 'aperture.py' is in the installtion folder so this should be easy to fix. Or am I doing something wrong. Just started tody with python.

 - Pip version: pip 9.0.1
 - Python version: 3.5.3
 - Operating system: Windows 10

**Comment by cbuhl** [comment]
I realize it's nearly a year since the last post in this thread, but for reference, I think the problem is non-functional implementation on python 3.x. I had similar issues with python 3.6, but it works under python 2.7.

**Comment by ZJ1224** [comment]
> I get a similar error message.
> 
> Upon evaluating the line
> 
> `from opticspy.ray_tracing import *`
> 
> I get
> 
> `ImportError: No module named 'aperture'`
> 
> The script 'aperture.py' is in the installtion folder so this should be easy to fix. Or am I doing something wrong. Just started tody with python.
> 
> * Pip version: pip 9.0.1
> * Python version: 3.5.3
> * Operating system: Windows 10



> I get a similar error message.
> 
> Upon evaluating the line
> 
> `from opticspy.ray_tracing import *`
> 
> I get
> 
> `ImportError: No module named 'aperture'`
> 
> The script 'aperture.py' is in the installtion folder so this should be easy to fix. Or am I doing something wrong. Just started tody with python.
> 
> * Pip version: pip 9.0.1
> * Python version: 3.5.3
> * Operating system: Windows 10

Hello, I just have the same problem, have you fixed it?
