### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by JGoutin** [Sterncat/opticspy#3]
Hello,
Is it possible to make opticspy Python 3 compatible ?

After a fast looking on your code, incompatibilities come mainly from `imports` and `prints`. 
The use of the following __future__ may help you to have a Python 2/3 compatible code.
```
from __future__ import print_function
from __future__ import absolute_import
```

And: Nice to see an optics library on Python, this was missing.

**Comment by Sterncat** [comment]
Hi
I think you are right! I need to do that. I will work on that! Thank you!

**Comment by MarkANorris** [comment]
After running the code through 2to3, I found only one instance of an import that needed to be manually changed before I could run your basic 3 lens example.

**Comment by Sterncat** [comment]
Hi, thanks for testing that! My python environment in my mac like a mess. I never test it under python 3. I should really use virtualenv more. 

Thanks!
