### ISSUE TITLE
Question: How can I use a custom glass definition

### ISSUE THREAD

**Issue by dibyendumajumdar** [Sterncat/opticspy#34]
I am trying to model lens design from patents. With regards to the glass type, I only have the refractive index and abbe number for d-line. For example, 1.79668 and 45.5. As this is a Nikon patent I tried to see if there was any glass in the Hikari catalog matching this, but there isn't.

Is there a way to add my own glass type just using these two attributes?

**Comment by Sterncat** [comment]
If you want to use Opticspy, you can try to change the glass index folder.
Add some customized glass.

Dibyendu Majumdar <notifications@github.com> 于2019年9月29日周日 上午2:27写道：

**Comment by dibyendumajumdar** [comment]
Okay thank you for the information.
