### ISSUE TITLE
Inserting a mirror & decentering

### ISSUE THREAD

**Issue by DrPaprikaa** [Sterncat/opticspy#39]
Hi, 
Thank you for this amazing library !
I couldn't find a way to add a mirror surface or to decenter surfaces, could you walk me through the steps please ?

Thanks,
DrPaprikaa

**Comment by Sterncat** [comment]
Hi Dr. Paprikaa,

I haven't made a mirror surface yet, also, no decenter function. It is more
like a personal practice for raytracing.

Thanks!
Xing

DrPaprikaa <notifications@github.com> 于2020年12月7日周一 下午12:25写道：

**Comment by DrPaprikaa** [comment]
I understand, thank you !

DrPaprikaa
