### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by atelierhide** [Sterncat/opticspy#4]
Hi!

Is there any reason this repo doesn't include `setup.py`?

I installed opticspy via pip in a clean environment, and it seems like some dependencies are missing.

I had to `pip install` or `conda install`:

* SciPy
* PyYAML

**Comment by Sterncat** [comment]
Hi!

Thank you for finding that! Indeed I forget to add PyYAML into the setup file. 
Also only the glass function use scipy.interpolate.interp1d, I just change it to a numpy.interp function. So the user don't need to include any scipy module in opticspy. If you want, you download a new version in github, or just change the file opticspy/ray_tracing/glass_function/refractiveIndex.py.

Thank you!

Best,

Marvin

**Comment by Sterncat** [comment]
Tell me if it works on your computer. If it works, I will close the issue. : )

**Comment by atelierhide** [comment]
Thanks. The `numpy.interp` looks fine, but the new version of `getMaterialFilename` in `refractiveIndex.py` doesn't work and should be replaced by the old version that comes with pip install.

**Comment by Sterncat** [comment]
I think the getMaterialFilename doesn't work is because the relative file path thing. I am still trying to figure out how to fix that. Now if you want to test the real ray tracing module, you should put the test file in the same folder as opticspy

**Comment by atelierhide** [comment]
Understood. I think this issue for missing dependencies should be closed. Thanks.
