### ISSUE TITLE
traceray() function in trace.py

### ISSUE THREAD

**Issue by DrPaprikaa** [Sterncat/opticspy#41]
Hi,

I am also trying to learning how ray-tracing works, and reading your code helps thank you !
Could you please explain the calculations you do in the `traceray()` function, in `ray_tracing/trace.py` ? In particular what are the calculations leading to `Pos_new `and `KLM_new `?

Thanks again

**Comment by Sterncat** [comment]
Hi Dr. Parprikaa,

It is from my Geometrical optics class notes from Dr. Dale Buralli at the
University of Rochester, the Institute of Optics. I try to attach it, but
the GitHub mailing system says it is too big. If you want to take a look at
the notes, please email directly via alex.fanxing@gmail.com. I can send it
to you.

Thanks!

Xing

DrPaprikaa <notifications@github.com> 于2020年12月13日周日 下午2:23写道：

**Comment by DrPaprikaa** [comment]
I just send you an email, thanks a lot ! 
I hope I will be able to wrap my head around ray-tracing soon, it's a challenge but I think I'm up to it ;)
