### ISSUE TITLE
Zernike fitting, given a list of 3D points (x,y,z).

### ISSUE THREAD

**Issue by sidgairo18** [Sterncat/opticspy#43]
How can we use the fitting function if we are given a 3D point cloud of (x,y,z) values where z is the elevation at point (x,y)?
It is not very apparent from the code.
Your help would be appreciated.

Thank you.

**Comment by Sterncat** [comment]
Yon only need to input Z if the center of the surface is (0,0). In code,
the x,y are [-1,1]. Before you input your Z, maybe you need to
adjust(scale) the data.

I will suggest using some other code/programs to do the fitting if you are
doing some serious project. These fitting codes are mainly for my own
practice 5 years ago.

Thanks!
Xing

Siddhartha Gairola <notifications@github.com> 于2020年12月30日周三 上午1:52写道：

**Comment by sidgairo18** [comment]
@Sterncat thank you for your response. Yes got that.
Thanks for your help 👍
